//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public long CartId { get; set; }
        public long CartCustId { get; set; }
        public long CartFoodId { get; set; }
        public string CartFoodName { get; set; }
        public long CartFoodQty { get; set; }
        public long CartFoodPrice { get; set; }
        public string CartFoodImage { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
